### ISSUE TITLE
can't login with latest commit

### ISSUE THREAD

**Issue by Akurosia** [xivapi/ffxiv-launcher#10]
Whenever i try to login after the latest commit, i get an error message on starting the game.
Please note that the actual game launches but on Selecting "Start Game" on title screen, an error is displayed.
With the version before that, everything works fine.

**Comment by vekien** [comment]
Hello,

Is this still an issue? I wonder if you need to delete the characters bit. That or SE put out a patch.

Just tested with 2 of my characters (one has a OTP) and it works fine.

**Comment by Akurosia** [comment]
Totally forgot this issue here.

Yeah it fixed itself after removing and reinstalling.
