### ISSUE TITLE
Move the "expansion" asset to the right.

### ISSUE THREAD

**Issue by AKoskovich** [xivapi/ffxiv-launcher#12]
Unless you full screen the news overlaps it. If you move it to the right that is no longer an issue. This happens on 3 machines, two of which are Linux based, but I installed it on Windows just to make sure it wasn't a derp with how I was compiling it.

I already have a patch for it for the Solus application.
https://github.com/ZVNexus/ffxiv/blob/master/files/exp-right.patch

**Comment by vekien** [comment]
Cheers for patch, I think i might make it smaller too

**Comment by vekien** [comment]
I've fixed in https://github.com/xivapi/ffxiv-launcher/releases/tag/0.2.9 by just removing it.
