### ISSUE TITLE
[Feature Request] Scrollbars on character list and news posts when resized

### ISSUE THREAD

**Issue by pigsflew** [xivapi/ffxiv-launcher#14]
If I make the UI smaller, the news block and character lists should become scrollable if the content is larger than the frame.

![image](https://user-images.githubusercontent.com/868821/57747478-904c6180-768a-11e9-80b8-468357d06732.png)

**Comment by vekien** [comment]
The character list one is already fixed just not released, might do the news too.

If you can make a PR with the change i will merge

**Comment by pigsflew** [comment]
Addressed in latest!
