### ISSUE TITLE
[Feature Request] Close the launcher when launched

### ISSUE THREAD

**Issue by Aireil** [xivapi/ffxiv-launcher#21]
If possible, to have the option of automatically closing the launcher when you launch the game. Unless it is already the current behavior and my launcher bugs?
Thank you.

**Comment by vekien** [comment]
I can add this as an option no problem!

**Comment by vekien** [comment]
I've added this into release: https://github.com/xivapi/ffxiv-launcher/releases/tag/0.3.2

If you want to try it out!

**Comment by Aireil** [comment]
Perfect, thank you! :)
