### ISSUE TITLE
[Feature Request] Preselect OTP field

### ISSUE THREAD

**Issue by Aireil** [xivapi/ffxiv-launcher#22]
This is a really minor feature request, but I figured it would be nice to have the OTP box preselected when choosing a character. So that you could just type it once you have clicked on the character, rather than clicking again on the OTP field.
Thank you.

**Comment by vekien** [comment]
Good idea and I've added it into the release for https://github.com/xivapi/ffxiv-launcher/releases/tag/0.3.2

**Comment by Aireil** [comment]
Again, perfect, thank you!
