### ISSUE TITLE
[Feature Request] OTP length requirement

### ISSUE THREAD

**Issue by Aireil** [xivapi/ffxiv-launcher#23]
I think it would be nice to be able to set a requirement on the length of the OTP. Not being able to start the game if the length requirement isn't met (as it'll fail at the connexion anyway). I don't think the length will change, but that could be a variable in the settings.

Not sure how that would get implemented (UI wise).

Thank you.

**Comment by Aireil** [comment]
I think the input box shouldn't be limited to 6 characters. If you press the same character twice mistakenly (before reaching the limit), the OTP will still be "valid" and just won't write the last character. However, you wrote 7 characters, so if it wasn't limited the client could tell that it's not a valid one.

Thank you.

**Comment by vekien** [comment]
Weird, it should reset when it loads the character a second time, I can remove the limit and rely on checks when you press enter.

**Comment by Aireil** [comment]
There seems to be a check in place if the length is smaller than 6 characters. The same check (but > 6) for the unlimited length would be perfect :).

**Comment by vekien** [comment]
I can't seem to replicate this, like i can't enter more than 6 at all, have you downloaded the latest version?

I can't enter more than 6 characters at all, even if i use the same characters.

the `minlength` and `maxlength` is set to 6, would you be able to record steps to reporduce the issue?

**Comment by Aireil** [comment]
Let's take an example, I think it'll be easier for me:
The correct OTP is 123456.
If you mistakenly write only 12346, the launcher will trigger an error and tell you the OTP is not valid (5 digits).
If you mistakenly press the same digit twice, e.g. 1223456, the launcher stops at 6 digits, so you'll have 122345 as OTP and it'll launch the game as it's a valid OTP (but it's not the correct OTP).

However, my idea is that in the second case, the launcher shouldn't stop the input at 6 digits, so you'll have 1223456 as OTP, which would also trigger an error being invalid (7 digits).
Edit: Just removing the 'maxlength="6"' in
```
<input type="text" class="otp2" id="otp2" placeholder="OTP" maxlength="6" minlength="6" required="" autofocus="">
```
 would "implement" my suggested behavior, as the checks seem to already be in place.

**Comment by vekien** [comment]
right i see what you mean, the top limit is causing issues if you make a type, that is easy to remove. I'll put it to like 10, if you make 4 typos, thats on you haha 💃

**Comment by vekien** [comment]
I've updated the release https://github.com/xivapi/ffxiv-launcher/releases/tag/0.3.5 if you want to try it.

**Comment by Aireil** [comment]
Perfect, thanks :).
