### ISSUE TITLE
Cant seem to add character

### ISSUE THREAD

**Issue by calmcacil** [xivapi/ffxiv-launcher#26]
Cant seem to add characters to this, grabbed latest version, but save button on character does nothing. checked console on inspect getting current errors.

app.js:1 XIVRequest:constructor -> Generated MachineID: 5cda39a3ee
app.js:1 No character.json file
app.js:1 Uncaught ReferenceError: $ is not defined
    at e.value (app.js:1)
    at HTMLButtonElement.<anonymous> (app.js:1)
    at HTMLHtmlElement.m (app.js:1)
    at HTMLHtmlElement.i.proxy (app.js:1)
value @ app.js:1
(anonymous) @ app.js:1
m @ app.js:1
i.proxy @ app.js:1

**Comment by vekien** [comment]
Might be due to changes on how Zepto was included, I'll have a look!

**Comment by calmcacil** [comment]
Suppose I'll add what I said on discord just in case its helpful. I tried older versions and this was apparent since 0.3.2 when I tried. (however that build claimed login details were wrong despite them not being.)

**Comment by vekien** [comment]
Updated https://github.com/xivapi/ffxiv-launcher/releases/tag/0.3.6 which should fix this!
