### ISSUE TITLE
My token expired before the 7 days.

### ISSUE THREAD

**Issue by Rai** [xivapi/ffxiv-launcher#6]
I noticed when i was logging in on the 5th (i think) day, and i was getting a lobby server error.

**Comment by vekien** [comment]
Hi, Yes SE have either modified this or the previous assumption of 7 days was a fluke. It can expire in 1 day, it is completely under SE's control.

This logic will likely be removed and User+Pass saving will take its place.

**Comment by Rai** [comment]
I see, thanks for the explanation!

**Comment by Rai** [comment]
Just to add to this, I re-authenticated, and this time it lasted 3 days. (Before spitting out the Lobby Server error)

**Comment by ArcaneDisgea** [comment]
Yeah from what I understand SE expires the tokens at random from 1 hour to 7 days later.

**Comment by vekien** [comment]
Closing as tokens are no longer used.
