### ISSUE TITLE
User-agent update

### ISSUE THREAD

**Issue by Genk1san** [xivapi/ffxiv-launcher#8]
The user-agent has been updated to SQEXAuthor/2.0.0(Windows 6.2; ja-jp; **45d19cc985** as of Patch 4.5.
[https://github.com/goaaats/FFXIVQuickLauncher/commit/869c498f9cf2d7f5874b293cb3c1c0a6a89b7e58#diff-004289fcc037d9af6249d1c7fa5b9d95](url)

**Comment by Akurosia** [comment]
its not only the user string this time. There are some additional adjustments needed

**Comment by Genk1san** [comment]
> its not only the user string this time. There are some additional adjustments needed

The original C# .net implementation currently functioning with the ID and hash generation update, does the Nodejs implementation needs more changes? Haven't had the chance to mess with it yet.

**Comment by Akurosia** [comment]
A fix was uploaded yesterday. It requires now more files to be hashed as well as the new region flag now.

**Comment by vekien** [comment]
This should be all working now, if you want to test.
